name: Download

on:
  schedule:
   - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download
        run: bash download.sh

      - name: Push to another repository
        uses: cpina/github-action-push-to-another-repository@master
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'core'
          destination-github-username: 'kostajh'
          destination-repository-name: 'mediawiki-all-extensions-all-skins'
          user-email: kosta@kostaharlan.net
